### ISSUE TITLE
Getting Data

### ISSUE THREAD

**Issue by rjb125** [JoeWilliamson32/Football-Analytics#1]
home_name = home_data['name']
away_name = away_data['name']

shows keyerror: name

**Comment by RishitJ1** [comment]
please help

**Comment by rjb125** [comment]
figured it out
thanks for the code anyway

**Comment by rjb125** [comment]
it is really helpful thank to u for posting this

**Comment by JW3297** [comment]
Thanks for the kind words. Any other issues let me know.
