### ISSUE TITLE
xG model

### ISSUE THREAD

**Issue by rjb125** [JoeWilliamson32/Football-Analytics#2]
To create xG model can u upload the shots data please

**Comment by RishitJ1** [comment]
or maybe the full .sav model

**Comment by rjb125** [comment]
please mate

**Comment by JoeWilliamson32** [comment]
I can see you've forked a whoscored scraper on your page - can you not just scrape the data yourself using that? You can play around with what fields to use as well (mine's not exactly perfect tbh). You probably only need ~30,000 shots so 3 seasons worth of data would suffice (just one league).

**Comment by rjb125** [comment]
I haven't ever scraped many matches at once to avoid getting IP banned and I don't use that scraper anymore btw.
Can't you just upload the .sav file?

**Comment by rjb125** [comment]
If possible give a way to contact you

**Comment by JoeWilliamson32** [comment]
Are you on twitter? Assume this is you - @MercFootball. Would be nice to at least credit my work if it is?

**Comment by rjb125** [comment]
Credit who? give a account to mention

**Comment by JoeWilliamson32** [comment]
As discussed - any other issues just reach out
